### ISSUE TITLE
Search book Student

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/Library-Management-System-Backend-#2]
As a student
I want a search button
So that I can search a particular book.

- [x]  BackEnd of SearchBook @Prasuna-Pokharel

**Comment by Prasuna-Pokharel** [comment]
**Here, the student can search the book they want from the library**
![2021-05-14 (19)](https://user-images.githubusercontent.com/80803470/118294530-89b38780-b4fa-11eb-80ad-3cb6ee424371.png)

**Comment by Prasuna-Pokharel** [comment]
**Here, the student can search the book they want from the library**
![2021-05-14 (19)](https://user-images.githubusercontent.com/80803470/118294885-ec0c8800-b4fa-11eb-8ad3-edc990ee9fa9.png)
