### ISSUE TITLE
Update Page

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/Library-Management-System-Backend-#3]
As an administrator
I want an update page
So that I can update reserved books.

- [x]  BackEnd development of Viewpage @Prasuna-Pokharel

**Comment by Prasuna-Pokharel** [comment]
**Here, Admin can update the books**
![2021-05-14 (21)](https://user-images.githubusercontent.com/80803470/118297909-7c000100-b4fe-11eb-8427-f0792fde1cc7.png)
![2021-05-14 (22)](https://user-images.githubusercontent.com/80803470/118297918-7f938800-b4fe-11eb-8e2e-6f987d338894.png)
![2021-05-14 (23)](https://user-images.githubusercontent.com/80803470/118297926-828e7880-b4fe-11eb-961f-fc702e66148b.png)
