### ISSUE TITLE
View Page STUDENT

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/Library-Management-System-Backend-#4]
As an Student
I want a View page
So that I can view overall books.

- [x]  BackEnd development of Viewpage @Prasuna-Pokharel

**Comment by Prasuna-Pokharel** [comment]
**Student can view all the books present in the library**
![viber_image_2021-05-15_11-29-18](https://user-images.githubusercontent.com/80803470/118349642-88717180-b571-11eb-80be-6bf0a6e0d8fe.jpg)
