### ISSUE TITLE
View Page ADMIN

### ISSUE THREAD

**Issue by Biraj18** [Supriya47/Library-Management-System-Backend-#5]
As an administrator
I want a View page
So that I can view overall books.

 

- [x] BackEnd development of viewpage ADMIN @Prasuna-Pokharel

**Comment by Prasuna-Pokharel** [comment]
**Here,admin can view all the books present in library**
![2021-05-14 (21)](https://user-images.githubusercontent.com/80803470/118297384-c7fe7600-b4fd-11eb-8e4f-971342ca140f.png)
